### ISSUE TITLE
metrics are not added as a list in config when using the add_a_metric script 

### ISSUE THREAD

**Issue by KaiWaldrant** [openproblems-bio/common_resources#17]
```
metrics:
    # A unique identifier for your metric (required).
    # Can contain only lowercase letters or underscores.
    name: accuracy
    # A relatively short label, used when rendering visualisarions (required)
    label: Accuracy
    # A one sentence summary of how this metric works (required). Used when 
    # rendering summary tables.
    summary: "FILL IN: A one sentence summary of this metric."
    # A multi-line description of how this component works (required). Used
    # when rendering reference documentation.
    description: |
      FILL IN: A (multi-line) description of how this metric works.
    # A reference key from the bibtex library at src/common/library.bib (required).
    reference: bibtex_reference_key
    # URL to the documentation for this metric (required).
    documentation_url: https://url.to/the/documentation
    # URL to the code repository for this metric (required).
    repository_url: https://github.com/organisation/repository
    # The minimum possible value for this metric (required)
    min: 0
    # The maximum possible value for this metric (required)
    max: 1
    # Whether a higher value represents a 'better' solution (required)
    maximize: true
```

should be:
```
  metrics:
    # A unique identifier for your metric (required).
    # Can contain only lowercase letters or underscores.
    - name: accuracy
      # A relatively short label, used when rendering visualisarions (required)
      label: Accuracy
      # A one sentence summary of how this metric works (required). Used when 
      # rendering summary tables.
      summary: "FILL IN: A one sentence summary of this metric."
      # A multi-line description of how this component works (required). Used
      # when rendering reference documentation.
      description: |
        FILL IN: A (multi-line) description of how this metric works.
      # A reference key from the bibtex library at src/common/library.bib (required).
      reference: bibtex_reference_key
      # URL to the documentation for this metric (required).
      documentation_url: https://url.to/the/documentation
      # URL to the code repository for this metric (required).
      repository_url: https://github.com/organisation/repository
      # The minimum possible value for this metric (required)
      min: 0
      # The maximum possible value for this metric (required)
      max: 1
      # Whether a higher value represents a 'better' solution (required)
      maximize: true
```
